稳定优化

diff --git a/sh/pre-svnmerge b/sh/pre-svnmerge
--- a/sh/pre-svnmerge
+++ b/sh/pre-svnmerge
@@ -1,9 +1,9 @@
 #!/bin/bash
 
+echo just test
+exit 0
 . ~/myscript/sh/cmdb
 . ~/myscript/sh/svn.sh
-
-echo pid is $$
 
 TEMP=$(getopt -o k:e:E:t:b:T:R:o:h --long rev:,types:,task:,email:,extra_mails:,trunk:,branch:,owner:,help -n $(basename -- $0) -- "$@")
 rev=
@@ -71,7 +71,6 @@ branch=$(echo $branch | perl -npe 's,\r, ,g')
 task=$(echo $task | perl -npe 's,\r,,g')
 
 branchs=$(
-    $branch
     for y in $branch;do
 	echo $y
     done
@@ -92,19 +91,19 @@ die() {
 
 function Exit_Status_Code () {
     if [ "$1" == 1 ];then
-	echo 分支不存在或者已关闭 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	echo 分支不存在或者已关闭 | mails_cm -i "svn pre-release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
 	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','分支不存在或者已关闭','1')";
     elif [ "$1" == 2 ];then
-	echo code合并内容为空 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	echo code合并内容为空 | mails_cm -i "svn pre-release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
 	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','code合并内容为空','2')";
     elif [ "$1" == 3 ];then
-	echo 反向合并,主干已合并较新的tag或分支 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	echo 反向合并,主干已合并较新的tag或分支 | mails_cm -i "svn pre-release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
 	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','反向合并,主干已合并较新分支','3')";
     elif [ "$1" == 4 ];then
-	echo 请提供对应tag,不支持分支预合并 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	echo 请提供对应tag,不支持分支预合并 | mails_cm -i "svn pre-release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
 	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','不支持分支预合并','4')";
     elif [ "$1" == 5 ];then
-	cat ~/tmp/merged/merge_mail_info.log | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cat ~/tmp/merged/merge_mail_info.log | mails_cm -i "svn pre-release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
 	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','$cfilenames','${rev:-0}','合并冲突','5')";
     else
 	echo
@@ -132,13 +131,13 @@ function Basecode() {
 	    svn log -l 1 $tag1  >~/tmp/merged/output.$$ 2>&1 || die "分支名输入错误或者分支已关闭"
 	    svn log -l 1 $tag2  >~/tmp/merged/output.$$ 2>&1 || die "分支名输入错误或者分支已关闭"
 	else
-	    svn log -l 1 $branch  >~/tmp/merged/output.$$ 2>&1 || die "分支名输入错误或者分支已关闭"
-	    
+	    svn log -l 1 $branch  >~/tmp/merged/output.$$ 2>&1 || die "分支名输入错误或者分支已关闭"	    
 	fi
 	
         if test -z $trunk;then
 	    #	    trunk=`echo $branch | perl -npe 's,Branch/.*/Develop,Trunk,g;s,Tag/.*/Develop,Trunk,g;s,Tag/.*?/,Trunk/,g'`
 	    trunk=`echo $branch | perl -npe 's,Branch/.*/Develop,Release_Trunk,g;s,Tag/.*/Develop,Release_Trunk,g;s,Tag/.*?/,Release_Trunk/,g'`
+	    svn list $trunk >& /dev/null || project=1
 	fi
 	
 	
@@ -311,10 +310,10 @@ function reverse_merge () {
 }
 
 function svn_from_tb_merged() {
-		(
+#		(
 		cd $Basetrunkcode
 		clean_workspace
-		
+
 		if [[ "$branch" =~ Tag ]];then
 		    local revision=`svn log | grep -w "${tag#*Tag/}"  | head -n 1 | awk -F "_" '{print $NF}'`
 		    local revision=${revision%*:}
@@ -339,12 +338,24 @@ function svn_from_tb_merged() {
 				
 		if  [ ! -z  "$revision" ];then
 		    reverse_merge
-		    st=`svn merge --dry-run $branch@$revision $branch@$head $trunk | grep -Ei 'conflicts|树冲突|正文冲突'`
+		    st=`svn merge --dry-run $branch@$revision $branch@$head . | grep -Ei 'conflicts|树冲突|正文冲突'`
 		    if [ -z "$st" ];then
-			return 0
+			echo
+			echo
+			echo "------pre-merge is ok------"
+			echo
+			echo
+			exit 0
+			
 			svn merge $branch@$revision $branch@$head
 		    else
-			echo "预合并冲突文件: $cfilenames" | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || exit
+			echo
+			echo
+			echo '------pre-merge is fails------'
+			echo
+			echo
+			exit 0
+			echo "预合并冲突文件: $cfilenames" | mails_cm -i "svn pre-release-merged faild------code merged from  ${tag3:-${branch#*tech/}}"
 			echo p | svn merge $branch@$revision $branch@$head
 			svn_conflict_files
 			svn_conflict_trees
@@ -370,12 +381,23 @@ function svn_from_tb_merged() {
 		    
 		    if [ ! -z  "$revision" ];then
 			reverse_merge
-			st=`svn merge --dry-run ${branch}@$revision $branch@$head $trunk | grep -Ei 'conflicts|树冲突|正文冲突'`
+			st=`svn merge --dry-run $branch@$revision $branch@$head . | grep -Ei 'conflicts|树冲突|正文冲突'`
 			if [ -z "$st" ];then
-			    return 0
+			    echo
+			    echo
+			    echo "======pre-merge is ok======"
+			    echo
+			    echo
+			    exit 0
 			    svn merge $branch@$revision $branch@$head
 			else
-			    echo "预合并冲突文件: $cfilenames" | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || exit
+			    echo
+			    echo
+			    echo '======pre-merge is fails======'
+			    echo
+			    echo
+			    exit 0
+			    echo "预合并冲突文件: $cfilenames" | mails_cm -i "svn pre-release-merged faild------code merged from  ${tag3:-${branch#*tech/}}"
 			    echo p | svn merge $branch@$revision $branch@$head
 			    svn_conflict_files
 			    svn_conflict_trees
@@ -388,7 +410,7 @@ function svn_from_tb_merged() {
 			    commit
 			)
 		fi
-		) > ~/tmp/merged/merge_mail_info.log
+#		) > ~/tmp/merged/merge_mail_info.log
 }
 
 function svn_from_bt_merged() {
@@ -471,10 +493,16 @@ locked-echo
 if test $types = add;then
 	for branch in ${branchs[@]};do
 		Basecode
-		if test -d $Basetrunkcode;then
+		if [ -z "$project" ];then
+		    if [ ! -d "$Basetrunkcode" ];then
+			(
+			    cd ../
+			    svn up .
+			)
+		    fi
 		    svn_from_tb_merged
 		else
-		    project_merge_create | mails_cm "${trunk#*Trunk/}------${info2}"
+		    exit 0
 		fi
 	done
 elif test $types = del;then
