change carrige return to blank space

diff --git a/sh/svnmerge b/sh/svnmerge
--- a/sh/svnmerge
+++ b/sh/svnmerge
@@ -4,49 +4,6 @@
 . ~/myscript/sh/svn.sh
 
 echo pid is $$
-#export TOP_PID=$$
-#trap 'exit 1' TERM
-
-die() {
-	(
-	echo "$@"
-	if test -e ~/tmp/merged/output.$$;then
-		echo
-		cat ~/tmp/merged/output.$$
-	fi
-	)
-	rm -f ~/tmp/merged/output.$$
-#	kill $$
-	Exit_Status_Code 1
-}
-
-function Exit_Status_Code () {
-    if [ "$1" == 1 ];then
-	echo 分支不存在或者已关闭 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
-	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','分支不存在或者已关闭','1')";
-    elif [ "$1" == 2 ];then
-	echo code合并内容为空 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
-	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','code合并内容为空','2')";
-    elif [ "$1" == 3 ];then
-	echo 反向合并,主干已合并较新的tag或分支 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
-	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','反向合并,主干已合并较新分支','3')";
-    elif [ "$1" == 5 ];then
-	cat ~/tmp/merged/merge_mail_info.log | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
-	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','$cfilenames','${rev:-0}','合并冲突','5')";
-    else
-	echo
-    fi
-    
-    echo > ~/tmp/merged/merge_mail_info.log && exit $1
-}
-
-function locked-echo() {
-    (
-	exec 9> ~/tmp/logs/svnmerge.lock
-	flock 9
-	echo "$@"
-    )
-}
 
 set -x
 
@@ -110,6 +67,61 @@ while true;do
     esac
 done
 
+export SMARTCM_EXTRA_MAIL="$email $extra_mails $owner"
+export -f Basecode
+export -f locked-echo
+
+branch=$(echo $branch | perl -npe 's,\r, ,g')
+task=$(echo $task | perl -npe 's,\r,,g')
+
+branchs=$(
+    $branch
+    for y in $branch;do
+	echo $y
+    done
+       )
+
+die() {
+	(
+	echo "$@"
+	if test -e ~/tmp/merged/output.$$;then
+		echo
+		cat ~/tmp/merged/output.$$
+	fi
+	)
+	rm -f ~/tmp/merged/output.$$
+#	kill $$
+	Exit_Status_Code 1
+}
+
+function Exit_Status_Code () {
+    if [ "$1" == 1 ];then
+	echo 分支不存在或者已关闭 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','分支不存在或者已关闭','1')";
+    elif [ "$1" == 2 ];then
+	echo code合并内容为空 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','code合并内容为空','2')";
+    elif [ "$1" == 3 ];then
+	echo 反向合并,主干已合并较新的tag或分支 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','反向合并,主干已合并较新分支','3')";
+    elif [ "$1" == 5 ];then
+	cat ~/tmp/merged/merge_mail_info.log | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','$cfilenames','${rev:-0}','合并冲突','5')";
+    else
+	echo
+    fi
+    
+    echo > ~/tmp/merged/merge_mail_info.log && exit $1
+}
+
+function locked-echo() {
+    (
+	exec 9> ~/tmp/logs/svnmerge.lock
+	flock 9
+	echo "$@"
+    )
+}
+
 function Basecode() {
 	if [[ "$branch" =~ Tag ]];then
 	    tag1=$branch
@@ -140,16 +152,6 @@ function Basecode() {
 	Basebranchcode=$Basebranch${branch#*Branch/}
 }
 
-export SMARTCM_EXTRA_MAIL="$email $extra_mails $owner"
-export -f Basecode
-export -f locked-echo
-
-branchs=$(
-$branch
-for y in $branch;do
-	echo $y
-done
-)
 
 function svn_conflict_files(){
 		    cfilenames=`svn st | grep ^C | awk '{print $2}'`
