持续优化

diff --git a/sh/svnmerge b/sh/svnmerge
--- a/sh/svnmerge
+++ b/sh/svnmerge
@@ -97,7 +97,7 @@ function Exit_Status_Code () {
 	echo 对应分支不存在或者已关闭 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
 	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','对应分支不存在或者已关闭','1')";
     elif [ "$1" == 2 ];then
-	echo code合并内容为空 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	echo code合并内容为空或为copy-to项目 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
 	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','code合并内容为空','2')";
     elif [ "$1" == 3 ];then
 	echo 反向合并,主干已合并较新的tag或分支 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
