modify svnmerge

diff --git a/sh/svnmerge b/sh/svnmerge
--- a/sh/svnmerge
+++ b/sh/svnmerge
@@ -14,14 +14,29 @@ die() {
 		echo
 		cat ~/tmp/merged/output.$$
 	fi
-	) | mails_cm -i "svn merged faild"
+	)
 	rm -f ~/tmp/merged/output.$$
 #	kill $$
 	Exit_Status_Code 1
 }
 
 function Exit_Status_Code () {
-    cat ~/tmp/merged/merge_mail_info.log | mails_cm -i "code merged from  ${tag3:-${branch#*tech/}}" || true
+    if [ "$1" == 1 ];then
+	echo 分支不存在或者已关闭 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','分支不存在或者已关闭','1')";
+    elif [ "$1" == 2 ];then
+	echo code合并内容为空 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','code合并内容为空','2')";
+    elif [ "$1" == 3 ];then
+	echo 反向合并,主干已合并较新的tag或分支 | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','反向合并,主干已合并较新分支','3')";
+    elif [ "$1" == 5 ];then
+	cat ~/tmp/merged/merge_mail_info.log | mails_cm -i "svn release-merged faild------code merged from  ${tag3:-${branch#*tech/}}" || true
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','$cfilenames','${rev:-0}','合并冲突','5')";
+    else
+	echo
+    fi
+    
     echo > ~/tmp/merged/merge_mail_info.log && exit $1
 }
 
@@ -141,10 +156,6 @@ function svn_conflict_files(){
 		    if [ -z "$cfilenames" ];then
 			return 0
 		    else
-			for cfilename in $cfilenames;do
-			    conflict_fils_path=/mnt/svn/conflict/$(now.)/$tag4/
-			    cp-with-dir-struct $conflict_fils_path $cfilename >& /dev/null
-			done
 			Exit_Status_Code 5
 		    fi
 }
@@ -257,7 +268,6 @@ function commit() {
     fi
 	
     if [ $info -eq 0 ];then
-	cmdb_mysql "insert into merge(branch_name,task,branch_date,path,owner,status,remarks,task_id) values ('${tag1:-$branch}','$task',now(),'${branch#*Develop/}','release','1','code合并内容为空','${task_id:-0}');"
 	Exit_Status_Code 2
     fi
 
@@ -269,9 +279,9 @@ function commit() {
     
     svn ci -m "$task
 Merged revision(s) $revision-$head  from ${tag3:-${branch#*tech/}}" && if [ -z $errors ];then
-	cmdb_mysql "insert into merge(branch_name,task,branch_date,path,owner,status,remarks,task_id) values ('${tag1:-$branch}','$task',now(),'${branch#*Develop/}','release','0','success','${task_id:-0}');"
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','success','0')";
     else
-	cmdb_mysql "insert into merge(branch_name,task,branch_date,path,owner,status,remarks,task_id) values ('${tag1:-$branch}','$task',now(),'${branch#*Develop/}','release','0','$info3','${task_id:-0}');"
+	cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','$info3','0')";
     fi	&& echo > ~/tmp/merged/merge_mail_info.log
 }
 
@@ -290,7 +300,6 @@ function reverse_merge () {
     h=${head#r*}
     r=${revision#r*}
     if [ $r -gt $h ];then
-	cmdb_mysql "insert into merge(branch_name,task,branch_date,path,owner,status,remarks,task_id) values ('${tag1:-$branch}','$task',now(),'${branch#*Develop/}','release','2','反向合并','${task_id:-0}');"
 	Exit_Status_Code 3
     fi
 }
@@ -443,7 +452,7 @@ function svn_db_merged() {
 function project_merge_create () {
     info2="根据分支已新建主干项目"
     export info2
-    svn list "$trunk" ||  cmdb_mysql "insert into merge(branch_name,task,branch_date,path,owner,status,remarks,task_id) values ('${tag1:-$branch}','$task',now(),'${branch#*Develop/}','release','0','$info2','${task_id:-0}');"
+    svn list "$trunk" ||  cmdb_mysql "insert into auto_merge(branch_name,date,owner,message,task_id,remarks,status) values ('${tag1:-$branch}',now(),'${extra_mails}','','${rev:-0}','$info2','0')";
     svn list "$trunk" ||  svn copy ${tag2:-$branch} ${trunk} --parents -m "新建主干项目"
 }
 
